### ISSUE TITLE
What is best behavior for out-of-order keys?

### ISSUE THREAD

**Issue by gkellogg** [w3c/json-ld-streaming#2]
On today's call we discussed a [comment](https://github.com/w3c/json-ld-streaming/pull/1#pullrequestreview-370009849) I made on PR #1 about how to deal with out-of-order keys.

There are two potential mechanisms:

1) Raise an error if an out-of-order key is encountered. Note that this might only be found after expanding the key, which itself can be order dependent.
2) Buffer until `@id` is seen.

The problem is more extensive than just `@id`, as `@type` needs to precede that, but so do any aliases of `@type`.

This satisfies https://github.com/w3c/json-ld-wg/issues/138.

**Comment by rubensworks** [comment]
After thinking about this a bit more, I agree with your comment that `@id` can appear out-of-order.

Concretely, this means that only `@context` MUST come first, following by `@type`. After that, keys (including `@id`) can come in any order, and parsers will have to buffer accordingly.

Additionally, I would add the suggestions for (streaming) document writers that `@id` SHOULD come after `@context` and `@type`, to avoid the need for buffering in parsers. (even if `@id` is a blank node)

Note that this is also exactly in line with my streaming parser implementation at the moment.

Do you agree with this? If so, I will update this in the PR.

**Comment by pchampin** [comment]
Sorry to chime in a little late, but that could lead to very pathological cases, like:
```
{
  "@context": {...},
  "prop1": "val1",
  "prop2": "val2",
  "prop3": {
    "prop4": "val4",
    "prop5": "val5",
    "prop6": {
      "prop7": "val7",
      "prop8": "val8",
      "@id": "#id3"
    },
    "@id": "#id2"
  },
  "@id": "#id1"
}
```

**Comment by rubensworks** [comment]
This would indeed be a sub-optimal order for streaming parsers that would lead to buffering until the very last node, but still valid. Optionally, a parser could emit a warning for such cases.

@pchampin Do you think we should revert to the previous requirement where `@id` MUST (instead of SHOULD) come before other properties.

**Comment by gkellogg** [comment]
I think warnings when thing are out of order, or if nesting is excessively deep might be the way to go.

Re-serializing with a serializer optimized for streaming could show how different parsing might be. 

Parsers might implement a “strict mode” to bail on out of order keys or deep nesting, but I think it would be wrong to fail to parse otherwise legal documents.
