### ISSUE TITLE
Positioning @type

### ISSUE THREAD

**Issue by iherman** [w3c/json-ld-streaming#8]
At present, the ordering requirement says:

> 1. `@context`
> 2. `@type` where its value indicates a type-scoped context.

which is of course technically correct. However, I wonder whether it is not simpler for the lambda user to simply require putting `@type` right after `@context`, no matter what.

Why? Many (most) readers of this document will be lambda users, who may not even be familiar with all the details of JSON-LD. They will "just" encode their data into JSON-LD. Ie, they may not fully grasp the "... type-scoped context" qualifier. Furthermore, they may not even be familiar with the context file they use, they would "just" include the reference and encode the data. Ie, they may not know whether a specific type has a type-scoped context defined or not. Finally, the `@context` file may change by adding a typed scoped context, which may make hitherto streamable json-ld files suddenly non-streamable.

**Comment by rubensworks** [comment]
Good points, I agree. I'll open a PR to remove the type-scoped context requirement for 2.

**Comment by pchampin** [comment]
I concur with @iherman, this subtley might be too technical for the average user. That being said, it might still be good to explain in a note why this is required (type-scoped contexts).

**Comment by pchampin** [comment]
Note that [example 8](https://w3c.github.io/json-ld-streaming/#example-8-valid-streaming-document-with-context-plain-type-id-and-other-properties) should then be revised or removed...

**Comment by jennet333** [comment]
> At present, the ordering requirement says:
> 
> 
> 
> > 1. `@context`
> 
> > 2. `@type` where its value indicates a type-scoped context.
> 
> 
> 
> which is of course technically correct. However, I wonder whether it is not simpler for the lambda user to simply require putting `@type` right after `@context`, no matter what.
> 
> 
> 
> Why? Many (most) readers of this document will be lambda users, who may not even be familiar with all the details of JSON-LD. They will "just" encode their data into JSON-LD. Ie, they may not fully grasp the "... type-scoped context" qualifier. Furthermore, they may not even be familiar with the context file they use, they would "just" include the reference and encode the data. Ie, they may not know whether a specific type has a type-scoped context defined or not. Finally, the `@context` file may change by adding a typed scoped context, which may make hitherto streamable json-ld files suddenly non-streamable.
> 
> 
> 
> 
Appeal allowed
